services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-grid-network
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium-grid
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: 2g
    networks:
      - jenkins-grid-network

networks:
  jenkins-grid-network:
    name: jenkins-grid-network
volumes:
  jenkins_home:
    name: jenkins_home
  
  