name: Build and Test Selenium Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Compose
        run: |
          docker-compose -v
          docker-compose up -d
      - name: Build Docker image
        run: |
          docker build -t selenium-python-test .

      - name: Run Selenium tests
        run: |
          docker run -e SELENIUM_HOST=http://selenium-grid:4444 --rm selenium-python-test